<?php

	/*
	Plugin Name: Single Sign On
	Plugin URI:
	Description: Simplifies user login by allowing to use a single set of credentials.
	Version: 1.0
	Author:  James
	Author URI: http://midtc.com/
	License:
	*/

	if (! defined('ABSPATH')) exit;

	include($_SERVER['DOCUMENT_ROOT'].'/wp-load.php');

	function single_sign_on_auto_login($user_id) {
	    if (!is_user_logged_in()) {
	        $user_login = get_userdata($user_id)->user_login;

	        $user = get_userdatabylogin($user_login);
	        $user_id = $user->ID;

	        wp_set_current_user($user_id, $user_login);
	        wp_set_auth_cookie($user_id);

	        do_action('wp_login', $user_login, $user);
	    }
	}


	function single_sign_on_login_cookie_drop($user_login, $user) {
		$response = array('error' => false, 'msg' => 'You have logged in successfully.');
		single_sign_on_cookie_dump('magic_logged_in_' . uniqid(), json_encode($response));
	}

	add_action('wp_login', 'single_sign_on_login_cookie_drop', 10, 2);

	function single_sign_on_generate_UUID() {
	    return sprintf(
	        '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
	        mt_rand(0, 0xffff),
	        mt_rand(0, 0xffff),
	        mt_rand(0, 0xffff),
	        mt_rand(0, 0x0fff) | 0x4000,
	        mt_rand(0, 0x3fff) | 0x8000,
	        mt_rand(0, 0xffff),
	        mt_rand(0, 0xffff),
	        mt_rand(0, 0xffff)
	    );
	}

	function single_sign_on_send_out_email($redirect, $email, $template_name, $template_html, $omeda_track_id, $email_subject, $additional_merged_variables = array(), $login_link, $test_email = true) {
	    global $c;

	    // Include OMEDA
	    echo INCLUDE_OMEDA();

	    $user_id = false;

	    if ($test_email) {
	        $user_id = get_current_user_id();
	    } else {
	        $user_id = get_user_by('email', $email);

	        if (!$user_id) {
	            $user_id = get_user_by('billing_email', $email);
	        }

	        if ($user_id) {
	            $user_id = $user_id->ID;
	        }

	        if (!$user_id) {
	            global $wpdb;
	            $table_name = $wpdb->prefix . 'usermeta';

	            $user_id = $wpdb->get_var(
	                $wpdb->prepare(
	                    "SELECT user_id FROM $table_name WHERE meta_key = %s AND meta_value = %s",
	                    'billing_email',
	                    $email
	                )
	            );
	        }
	    }

	    if (!is_null($redirect) && !empty($redirect)) {
	    	$login_link .= '#' . $redirect;
	    }

	    $host = esc_url(home_url());
	    $path = '/magic/';

	    $first_name = get_user_meta($user_id, 'first_name', true) ?: get_user_meta($user_id, 'billing_first_name', true) ?: null;
	    $last_name = get_user_meta($user_id, 'last_name', true) ?: get_user_meta($user_id, 'billing_last_name', true) ?: null;

	    $email_subject = stripslashes($email_subject);

	    //$html_content = '<p><b>This text was auto-generated by our development team and serves as a temporary placeholder until the finalized content is provided.</b></p>';
		$html_content = '';
	    $html_content .= empty($first_name) && empty($last_name) ? '<p>Dear user,</p>' : '<p>Dear ' . $first_name . ',</p>';

	    $html_content .= <<<HTML
    
	    <p>You've requested a convenient way to access your account – a magic link! To log in effortlessly, simply click the link below:</p>
	    
	    <p><a href="{$host}{$path}@{login_link}@" target="_blank">{$host}{$path}@{login_link}@</a></p>
	    
	    <p>This magic link will grant you instant access to your account. For your security, please keep it safe and avoid sharing it with others. If you didn't request this magic link or have any questions, please feel free to reach out to our friendly support team.</p>
	    
	    <p>Thank you for choosing our service!</p>
	    
	    <p>Sincerely,</p>
	    <p>The Artists Network Team</p>
HTML;

		$mergedVariables[0]['login_link'] = $login_link;

	    $fields = array(
	        'TrackId' => $omeda_track_id,
	        'EmailAddress' => $email,
	        'FirstName' => $first_name,
	        'LastName' => $last_name,
	        'Subject' => $email_subject,
	        'HtmlContent' => $html_content,
	        'Preference' => 'HTML',
	        'MergeVariables' => $mergedVariables
	    );

	    $send_payload_to_omeda = omedaCurl("{$c('ON_DEMAND_ENDPOINT')}{$c('OMEDA_DIRECTORY')['send_email']}", json_encode($fields));

	    $send_decode_omeda_payload_status = $send_payload_to_omeda[1];

		if($send_decode_omeda_payload_status == 400) {
			return false;
		}

		if($send_decode_omeda_payload_status == 404) {
			return false;
		}

		if($send_decode_omeda_payload_status !== 200) {
			return false;
		}

		$send_decode_omeda_payload = json_decode($send_payload_to_omeda[0], true);

		if(!isset($send_decode_omeda_payload)) {
			return false;
		}

	    return $send_payload_to_omeda;
	}

	function single_sign_on_login_encrypt($data, $passphrase) {
	    $secret_key = hex2bin($passphrase);
	    $iv = openssl_random_pseudo_bytes(12); // Generate a random IV (Initialization Vector)
	    $encrypted_data = openssl_encrypt(json_encode($data), 'aes-256-gcm', $secret_key, OPENSSL_RAW_DATA, $iv, $tag);
	    
	    // Base64 encode the encrypted data, IV, and tag for storage
	    $encoded_data = base64_encode(json_encode([
	        'data' => base64_encode($encrypted_data),
	        'iv'   => base64_encode($iv),
	        'tag'  => base64_encode($tag),
	    ]));
	    
	    return $encoded_data;
	}

	function single_sign_on_login_decrypt($data, $passphrase) {
	    $secret_key = hex2bin($passphrase);
	    $json = json_decode(base64_decode($data), true);
	    $iv = base64_decode($json['iv']);
	    $tag = base64_decode($json['tag']);
	    $encrypted_data = base64_decode($json['data']);
	    $decrypted_data = openssl_decrypt($encrypted_data, 'aes-256-gcm', $secret_key, OPENSSL_RAW_DATA, $iv, $tag);
	    
	    return json_decode($decrypted_data, true);
	}

	function single_sign_on_code_generation($user_data) {
		$user_id = $user_data->ID;
		$code = sprintf('%06d', rand(0, 999999));

		$assign_sso = update_user_meta($user_id, 'midtc_single_sign_on_code',  array('code' => $code, 'epoch' => time()));

		if(!$assign_sso) {
			return false;
		}

		return $code;
	}

	function single_sign_on_code_check($user_data) {
		$user_id = $user_data->ID;
		$meta_key = 'midtc_single_sign_on_code';

		$user_meta = get_user_meta($user_id, $meta_key, true);

		if ($user_meta) {
		    return $user_meta;
		}

		return false;
	}

	add_shortcode('single_sign_on_form', 'single_sign_on_form_callback');

	function single_sign_on_form_callback() {
    $output = <<<HTML
    <style>

        .email-input {
            width: 100%;
            padding: 10px;
            border: none;
            border-bottom: 2px solid #3498db;
            outline: none;
            font-size: 16px;
            margin-bottom: 20px;
        }

        .email-label {
            display: block;
            text-align: left;
            margin-bottom: 5px;
            color: #555;
            font-weight: bold;
        }

        .sign-in-button {
            background-color: #3498db;
            color: #fff;
            border: none;
            border-radius: 4px;
            padding: 10px 20px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }

        .sign-in-button:hover {
            background-color: #2980b9;
        }

        .sso-form-container {
            text-align: left;
		    max-width: 600px;
		    margin: 0 auto;
		}

        .notification {
		  padding: 15px;
		  margin-bottom: 20px;
		  font-size: 14px;
		  border: 1px solid transparent;
		  border-radius: 4px;
		  color: #fff;
		  background-color: #17a2b8;
		  border-color: #17a2b8;
		}

		.notification.success {
		  background-color: #28a745;
		  border-color: #28a745;
		}

		.notification.warning {
		  background-color: #ffc107;
		  border-color: #ffc107;
		}

		.notification.danger {
		  background-color: #dc3545;
		  border-color: #dc3545;
		}

		.d-none {
			display: none !important;
		}
    </style>
        <div class="sso-form-container">
        	<div class="notification success d-none"></div>
	        <input type="email" id="email" class="sso-email-input" placeholder="Enter your email">
	        <button class="sso-sign-in-button" data-action="send-link">Send Magic Link</button>
	    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var parentContainer = document.querySelector('.sso-form-container');
            var ssoSignInButton = parentContainer.querySelector('.sso-sign-in-button');
            
            ssoSignInButton.addEventListener('click', function () {
            	var emailInput = document.querySelector('.sso-email-input');
                const email = emailInput.value;

                var ssoSignInButtonAction = ssoSignInButton.getAttribute('data-action');

                if(ssoSignInButtonAction == 'send-link') {
                	fetch('?request=single_sign_on&email=' + email, {
	                    method: 'GET',
	                    headers: {
	                        'Content-Type': 'application/json',
	                    }
	                })
	                .then(response => response.json())
	                .then(data => {
	                	const dataError = data['error'];
						const msg = data['msg'];

						var parentContainer = document.querySelector('.sso-form-container');
						const notification = parentContainer.querySelector('.notification');

						notification.classList.toggle('success', !dataError);
						notification.classList.toggle('danger', dataError);
						notification.classList.remove('d-none');
						notification.textContent = msg;

						if(!dataError) {
							var ssoSignInButton = parentContainer.querySelector('.sso-sign-in-button');

							ssoSignInButton.textContent = 'Magic link sent...';
							ssoSignInButton.setAttribute('data-action', 'link-sent');

							emailInput.setAttribute('disabled', '');
						}
	                })
	                .catch(error => {
	                    console.error('Error:', error);
	                });
                }    
            });
        });
    </script>
HTML;

    return $output;
	}

	function single_sign_on_code_processing_rest_api() {
		$request_type = isset($_GET['request']) ? sanitize_text_field($_GET['request']) : null;

		if(!$request_type) {
			return;
		}

		if($request_type != 'single_sign_on' && $request_type != 'single_sign_on_check') {
			return;
		}

		if($request_type == 'single_sign_on_check') {
			$output['logged_in'] = is_user_logged_in();

			die(json_encode($output));
		}

		$output = ['error' => true, 'msg' => 'Parameter issue'];

		if(is_user_logged_in()) {
			$output['msg'] = "You are already logged in at the moment.";

			die(json_encode($output));
		}

		$email_address = isset($_GET['email']) ? (sanitize_email($_GET['email']) ?: sanitize_text_field($_GET['email'])) : null;

		if(!$email_address) {
			$output['msg'] = 'You haven\'t provided a username or email address.';

			die(json_encode($output));
		}

		$user = get_user_by('email', $email_address) ?: get_user_by('login', $email_address);

	    if ($user) {
	        $user_id = $user->ID;
	        $user_data = get_userdata($user_id);

			if($request_type != 'single_sign_on') {
				die(json_encode($output));
			}

			$meta_key = 'midtc_single_sign_on_data';

			$pull_user_sign_on_data = get_user_meta($user_id, $meta_key, true);

			if ($pull_user_sign_on_data) {
			    if (!((time() - $pull_user_sign_on_data['epoch']) > 60)) {
					$output['msg'] = "We've already sent a magic link. Please wait for 60 seconds before trying again.";

					die(json_encode($output));
			    }
			}

			$user_email = $user_data->user_email;
	        $assigned_sso = single_sign_on_code_generation($user_data);
	        $assigned_uuid = single_sign_on_uuid($user_data);

			if (!$assigned_sso || !$assigned_uuid) {
			    $output['msg'] = "An error occurred while generating a magic link. Please attempt this again at a later time.";
			}

        	$data = ['email' => $user_email, 'epoch' => time(), 'sso' => $assigned_sso, 'uuid' => $assigned_uuid];

        	$assigned_data = single_sign_on_apply_data($user_data, $data);

        	if (!$assigned_data) {
			    $output['msg'] = "An error occurred while generating a magic link. Please attempt this again at a later time.";
			}

			$single_sign_on_login_code = $assigned_uuid;

			$redirect = isset($_GET['redirect']) ? esc_url($_GET['redirect']) : null;

            $send_sso_email = single_sign_on_send_out_email($redirect, $user_email, null, null, 'GPM240318014', 'Your Artists Network Magic Link', null, $single_sign_on_login_code, true);

            if ($send_sso_email) {
                $output['error'] = false;
                $output['msg'] = "Please check your email for the magic link to log into your account. It will expire in <span id='countdown'>60</span> seconds.";
            } else {
                $output['msg'] = "Error sending the magic link. Please try again later.";
            }
	        
	    } else {
	        $output['msg'] = 'Please double-check that you\'ve entered the right username or email. We couldn\'t locate an account associated with <b>' . $email_address . '</b>.';
	    }

		die(json_encode($output));
	}

	function single_sign_on_apply_data($user_data, $data) {
		$user_id = $user_data->ID;

		$assign_data = update_user_meta($user_id, 'midtc_single_sign_on_data',  $data);

		if(!$assign_data) {
			return false;
		}

		return true;
	}

	function single_sign_on_uuid($user_data) {
		$user_id = $user_data->ID;
		$generated_uuid = single_sign_on_generate_UUID();

		$assign_uuid = update_user_meta($user_id, 'midtc_single_sign_on_uuid',  $generated_uuid);

		if(!$assign_uuid) {
			return false;
		}

		return $generated_uuid;
	}

	add_action('init', 'single_sign_on_code_processing_rest_api');

	function single_sign_on_cookie_dump($name, $value) {
	    $expirationTime = time() + 3600;

	    setcookie($name, $value, $expirationTime, "/");
	}

	function single_sign_on_user_data_reset($user_data) {
		$user_id = $user_data->ID;

		delete_user_meta($user_id, 'midtc_single_sign_on_uuid');
		delete_user_meta($user_id, 'midtc_single_sign_on_code');
		delete_user_meta($user_id, 'midtc_single_sign_on_data');
	}

	function single_sign_on_pattern_check($wp) {
	    $request_path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

	    if (!(stripos($request_path, 'magic') !== false)) {
	        return;
	    }

	    $pathSegments = explode('/', $request_path);

	    if (count(explode('/', trim($request_path, '/'))) > 0 && in_array($pathSegments[1], ['magic']) && isset($pathSegments[2])) {
	    	$user_single_sign_on_uuid = isset($pathSegments[2]) ? sanitize_text_field($pathSegments[2]) : null;

	    	$response = array('error' => true, 'msg' => 'A problem has arisen while attempting to log you in using a magic link.');

	    	if(!$user_single_sign_on_uuid) {
	    		single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

				die(wp_redirect(home_url('/my-account/')));
	    	}

	    	global $wpdb;

			$sql = $wpdb->prepare("
			    SELECT DISTINCT u.ID, u.user_login
			    FROM {$wpdb->users} u
			    JOIN {$wpdb->usermeta} um ON u.ID = um.user_id
			    WHERE um.meta_key = %s
			      AND um.meta_value = %s
			    LIMIT 1
			", 'midtc_single_sign_on_uuid', $user_single_sign_on_uuid);

			$result = $wpdb->get_row($sql);

			if ($result) {
			    $user_id = $result->ID;
				$user_data = get_userdata($user_id);


				if (!$user_data) {
					single_sign_on_cookie_dump('login_error_' . uniqid(), $response);
					
					die(wp_redirect(home_url('/my-account/')));
				}

			    $user_login = $result->user_login;

			    $user_single_sign_on_data = get_user_meta($user_id, 'midtc_single_sign_on_data', true);
			    $user_single_sign_on_code_data = get_user_meta($user_id, 'midtc_single_sign_on_code', true);

			    if(!$user_single_sign_on_data || !$user_single_sign_on_code_data) {
			    	$response['msg'] = 'An issue has occurred while attempting to log you in using a magic link.';

			    	single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

			    	single_sign_on_user_data_reset($user_data);

					die(wp_redirect(home_url('/my-account/')));
			    }

			    $user_single_sign_on_data_email = $user_single_sign_on_data['email'];
			    $user_single_sign_on_data_epoch = $user_single_sign_on_data['epoch'];
			    $user_single_sign_on_data_sso = $user_single_sign_on_data['sso'];
			    $user_single_sign_on_data_uuid = $user_single_sign_on_data['uuid'];

			    $user_single_sign_on_code_data_sso = $user_single_sign_on_code_data['code'];
			    $user_single_sign_on_code_data_epoch = $user_single_sign_on_code_data['epoch'];

			    if(!($user_single_sign_on_data_uuid == $user_single_sign_on_uuid)) {
			    	$response['msg'] = 'An unknown issue has occurred while attempting to log you in using a magic link.';

			    	single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

			    	single_sign_on_user_data_reset($user_data);

					die(wp_redirect(home_url('/my-account/')));
			    }

			    if(!($user_single_sign_on_code_data_sso == $user_single_sign_on_code_data_sso)) {
			    	$response['msg'] = 'An unexpected problem has arisen while trying to log you in using a magic link.';

			    	single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

			    	single_sign_on_user_data_reset($user_data);

					die(wp_redirect(home_url('/my-account/')));
			    }

			    $user_single_sign_on_data_epoch_check = time() - $user_single_sign_on_data_epoch;

			    if (($user_single_sign_on_data_epoch_check > 300)) {
					$response['msg'] = "That magic link has expired. Kindly request a new one for verification.";

			    	single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

			    	single_sign_on_user_data_reset($user_data);

					die(wp_redirect(home_url('/my-account/')));
				}

				$user_single_sign_on_code_data_epoch_check = time() - $user_single_sign_on_code_data_epoch;

			    if (($user_single_sign_on_code_data_epoch_check > 300)) {
					$response['msg'] = "That magic link has expired. Kindly request a new one to log into your account.";

			    	single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

			    	single_sign_on_user_data_reset($user_data);

					die(wp_redirect(home_url('/my-account/')));
				}

				single_sign_on_auto_login($user_id);

		        die(wp_redirect(home_url('/my-account/')));
			} else {
				$response['msg'] = "That magic link invalid. Kindly request a new one to log into your account.";

		    	single_sign_on_cookie_dump('magic_error_' . uniqid(), json_encode($response));

		    	single_sign_on_user_data_reset($user_data);

				die(wp_redirect(home_url('/my-account/')));
			}
	    	
	    	die(wp_redirect(home_url('/')));
	    } else {
	        return;
	    }
	}

	function single_sign_on_login($user_login, $user) {
		$user_id = $user->ID;
	   	
	   	update_user_meta($user_id, 'midtc_single_sign_on_uuid', '');
		update_user_meta($user_id, 'midtc_single_sign_on_code', '');
		update_user_meta($user_id, 'midtc_single_sign_on_data', '');
	}

	//add_action('wp_login', 'single_sign_on_login', 10, 2);

	add_action('parse_request', 'single_sign_on_pattern_check');

	add_action('wp_head', 'single_sign_on_redirect_check');

	function single_sign_on_redirect_check() {
		wp_enqueue_script('single-sign-on-redirect-script', plugin_dir_url(__FILE__) . 'assets/js/login-redirect-script.js?' . time());
	}

	function single_sign_on_login_form_button() {
		wp_enqueue_script('single-sign-on-script', plugin_dir_url(__FILE__) . 'assets/js/script.js?' . time());
 		wp_enqueue_style('single-sign-on-style', plugin_dir_url(__FILE__) . 'assets/css/style.css?' . time());

		$html_content = '<button type="button" class="woocommerce-Button button float-left" name="magic" value="Send Magic Link">Magic Link</button><button type="button" class="woocommerce-Button button float-right" name="password" value="Use Password">Use Password</button>';
		
		return $html_content;
	}